kddcup:
  ae_latent_dimension: 8
  encoder_FCN_to_latent:
    dims:
      - 64
      - 32
    activation: 'tanh'

  encoder_discrete_xform:
    service:
      dims:
        - 8
      activation: 'none'
  encoder_real_xform:
    dims:
      - 16
    activation: 'tanh'
  decoder_FC_from_latent:
    dims:
        - 32
        - 64
    activation:  'tanh'
  decoder_discrete_xform:
    protocol_type:
      dims: ~
      activation: 'tanh'
    service:
      dims: ~
      activation: 'tanh'
    flag:
      dims: ~
      activation: 'tanh'
    land:
      dims: ~
      activation: 'tanh'
    logged_in:
      dims: ~
      activation: 'tanh'
    is_guest_login:
      dims: ~
      activation: 'tanh'
  decoder_real_xform:
    dims: ~
    activation: 'tanh'
  real_loss_func: 'mse'
  discrete_loss_func: 'categorical_crossentropy'
  epochs: 30
  batch_size: 256
  LR: 0.0005
  max_gamma: 10
  ae_dropout: 0.2
  anomaly_ratio : 0.2

nb15:
  ae_latent_dimension: 8
  encoder_FCN_to_latent:
    dims:
      - 48
      - 16
    activation: 'tanh'
  encoder_discrete_xform:
    proto:
      dims:
        - 8
      activation: 'none'
  encoder_real_xform:
    dims:
      - 16
    activation: 'tanh'
  decoder_FC_from_latent:
    dims:
        - 16
        - 48
    activation:  'tanh'
  decoder_discrete_xform:
    protocol_type:
      dims: ~
      activation: 'tanh'
    service:
      dims: ~
      activation: 'tanh'
    flag:
      dims: ~
      activation: 'tanh'
    land:
      dims: ~
      activation: 'tanh'
    logged_in:
      dims: ~
      activation: 'tanh'
    is_guest_login:
      dims: ~
      activation: 'tanh'
  decoder_real_xform:
    dims: ~
    activation: 'tanh'

  real_loss_func: 'mse'
  discrete_loss_func: 'categorical_crossentropy'
  epochs : 30
  batch_size : 256
  anomaly_ratio : 0.1
  LR: 0.0005
  ae_dropout: 0.2

nsl_kdd:
  ae_latent_dimension: 8
  encoder_FCN_to_latent:
    dims:
      - 32
      - 16   
    activation: 'tanh'

  encoder_discrete_xform:
    service:
      dims:
        - 8
      activation: 'none'
  encoder_real_xform:
    dims:
      - 12
    activation: 'tanh'
  decoder_FC_from_latent:
    dims:
        - 16
        - 32
    activation:  'tanh'
  decoder_discrete_xform:
    protocol_type:
      dims: ~
      activation: 'tanh'
    service:
      dims: ~
      activation: 'tanh'
    flag:
      dims: ~
      activation: 'tanh'
    land:
      dims: ~
      activation: 'tanh'
    logged_in:
      dims: ~
      activation: 'tanh'
    is_guest_login:
      dims: ~
      activation: 'tanh'
  decoder_real_xform:
    dims: ~
    activation: 'tanh'
  real_loss_func: 'mse'
  discrete_loss_func: 'categorical_crossentropy'
  epochs: 30
  batch_size: 256
  LR: 0.0005
  ae_dropout: 0.2
  anomaly_ratio : 0.1
  

gureKDD:
  ae_latent_dimension: 10
  encoder_FCN_to_latent:
    dims:
      - 40
      - 32
      - 16
    activation: 'tanh'

  encoder_discrete_xform: ~
  encoder_real_xform:
    dims:
      - 8
    activation: 'tanh'
  decoder_FC_from_latent:
    dims:
        - 16
        - 32
           
    activation:  'tanh'
  decoder_discrete_xform:
    protocol_type:
      dims: ~
      activation: 'tanh'
    service:
      dims: ~
      activation: 'tanh'
    flag:
      dims: ~
      activation: 'tanh'
    land:
      dims: ~
      activation: 'tanh'
    logged_in:
      dims: ~
      activation: 'tanh'
    is_guest_login:
      dims: ~
      activation: 'tanh'
  decoder_real_xform:
    dims: ~
    activation: 'tanh'

  real_loss_func: 'mse'
  discrete_loss_func: 'categorical_crossentropy'
  epochs: 30
  batch_size: 256
  LR: 0.001
  ae_dropout : 0.2
  anomaly_ratio : 0.1

 

kddcup_neptune:
  ae_latent_dimension: 8
  encoder_FCN_to_latent:
    dims:
      - 64
      - 32
    activation: 'tanh'

  encoder_discrete_xform:
    service:
      dims:
        - 8
      activation: 'none'
  encoder_real_xform:
    dims:
      - 16
    activation: 'tanh'
  decoder_FC_from_latent:
    dims:
        - 32
        - 64
    activation:  'tanh'
  decoder_discrete_xform:
    protocol_type:
      dims: ~
      activation: 'tanh'
    service:
      dims: ~
      activation: 'tanh'
    flag:
      dims: ~
      activation: 'tanh'
    land:
      dims: ~
      activation: 'tanh'
    logged_in:
      dims: ~
      activation: 'tanh'
    is_guest_login:
      dims: ~
      activation: 'tanh'
  decoder_real_xform:
    dims: ~
    activation: 'tanh'

  real_loss_func: 'mse'
  discrete_loss_func: 'categorical_crossentropy'
  epochs: 30
  batch_size: 256
  LR: 0.001
  ae_dropout : 0.2
  anomaly_ratio : 0.1