kddcup:
  anomaly_ratio : 0.25
  num_anomaly_sets: 5
  dsvdd:
    layer_dims:
      - 64
      - 32
      - 16
    num_epochs: 100
    ae_epochs: 250
    batch_size: 256
    warm_up_epochs: 20
    LR: 0.001
  dcn:
    layer_dims:
      - 64
      - 34
      - 16
    epochs_1: 15
    epochs_2: 25
    batch_size: 512
  dagmm:
    encoder_layers:
      activation: 'tanh'
      layer_dims:
        - 60
        - 30
        - 10
    ae_latent_dimension: 1
    decoder_layers:
      activation: 'tanh'
      layer_dims:
        - 10
        - 30
        - 60
    gmm:
      num_components: 2
      FC_layer:
        dims:
          - 10
        activation: 'tanh'
      FC_dropout: 0.5
    num_epochs: 400
    batch_size: 1024